name: Daily ETL Pipeline

on:
  schedule:
    - cron: '30 10 * * *'   # Every day at 10 AM UTC (4:00 AM CST)
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      # ─────────────────────────────────────────────────────────────
      - name: Request token and trigger reporting run
        id: reporting
        uses: Wandalen/wretry.action@v2
        with:
          command: |
            # Fetch access token
            response=$(curl -s -w "\n%{http_code}" -X POST \
              -H "Content-Type: application/json" \
              -d '{"token":"all"}' \
              https://api.agmtechnology.com/token)

            http_status=$(echo "$response" | tail -n1)
            body=$(echo "$response" | sed '$d')

            if [ "$http_status" != "200" ]; then
              echo "Token request failed with status $http_status"
              exit 1
            fi

            access_token=$(echo "$body" | jq -r '.access_token')
            if [ "$access_token" = "null" ] || [ -z "$access_token" ]; then
              echo "access_token not found in response"
              exit 1
            fi

            # Trigger reporting run
            status=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: Bearer $access_token" \
              -X GET https://api.agmtechnology.com/reporting/run)

            echo "http_status=$status" >> "$GITHUB_OUTPUT"

            if [ "$status" != "200" ]; then
              echo "Reporting run request failed with status $status"
              exit 1
            fi
          attempt_limit: 24 # 1 original + 23 retries (4 hours)
          attempt_delay: 600000 # 10-minute pause (ms)
          
  notify-success:
    needs: etl
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send success email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Daily ETL Pipeline SUCCEEDED"
          to: aa@agmtechnology.com,cr@agmtechnology.com
          from: aa@agmtechnology.com
          body: |
            The ETL Pipeline completed successfully.
          
  notify-failure:
    needs: etl
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Daily ETL Pipeline FAILED"
          to: aa@agmtechnology.com,cr@agmtechnology.com
          from: aa@agmtechnology.com
          body: |
            The ETL Pipeline failed.